### ISSUE TITLE
--force?

### ISSUE THREAD

**Issue by zvezdochiot** [rbrito/pdfsizeopt#3]
Maybe add force mode?

**Comment by zvezdochiot** [comment]
⚠️ Not resolved !!!

**Comment by rbrito** [comment]
On March 30, 2021 2:03:06 PM GMT-03:00, "звездочёт" ***@***.***> wrote:
>⚠️ Not resolved !!!


Of course it is not fixed.

1 - just from your telegraphic "bug" reports of one word only, I can't really tell what you could possibly mean...
2 - my mother is almost dying and I can only care about her health and distracting myself from her condition (tweaking one script or another that interests me the most as a way to kill the time)
3 - I am currently not healthy also, and you may have seen my status here on github that I still have to go through a 3rd kidney surgery in a few weeks...

So, if you can't really do a better job then write a one word-only bug report (and this comment also applies to your other bug reports), I fear that I can't really help you with anything.

Hope this clarifies the situation,

Rogério Brito.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zvezdochiot** [comment]
I just clean my PRs and issues from the hopeless ones.
