### ISSUE TITLE
1

### ISSUE THREAD

**Issue by necros2k7** [rbrito/pdfsizeopt#5]

**Comment by rbrito** [comment]
On July 27, 2020 6:13:25 AM GMT-03:00, necros2k7 <notifications@github.com> wrote:
>subj

Sorry,

That's not going to happen, because I am already swamped and I don't know about PDF's as well as @pts does.

Regards,

Rogério Brito.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
